### PR TITLE
convert EOL to unix

### PR DESCRIPTION
**Pull request by paulwratt**
the last commit on master meant there are no more problem converting the files.

Vim was detecting different charactersets in some files, which I believe are characters over 127, so the file shows as "converted" when you first load it up. Those files, along with the one that had inlined control characters, we the same ones `dos2unix` had problems with.

### CODE REVIEW

**Review by paulwratt — COMMENTED** [review]
this is only *.c and *.h files. I should be fine to leave the other files

I did notice the beta tag here 
https://github.com/freemint/highwire/pull/2/files#diff-741f0195763b008706a42eea7b8c9a1f1c975ea578ccf2b0433ff9f45ddc266e

<s>that means I _dont_ have the beta6 source.</s> Also is that `a` character a control char or a AtariST char

(review: I cant approve this PR btw - or request changes - just comment)

**Comment by mikrosk** [comment]
> (review: I cant approve this PR btw - or request changes - just comment)

Are you sure you know how Github and PRs work? For a PR you don't need write access and since Thorsten already gave you one, you don't need to create and/or approve your own PRs.

**Comment by th-otto** [comment]
Yes, the encoding files (en_atari.h and en_bics.h) have the atari non-ascii characters embedded. I think it's better to replace them with their hex-codes, to avoid problems when loading in text-editors on unix/windows.

The ```a``` control character is the same, an atari beta character (0xe1).

About the beta6 source: did you compare the source files to the ones you got from Peter? And can you send me the files or upload them somewhere?

I've accepted your invite and added you to the "gem" team. That should allow you to directly push to the repo. If not, please let me know.

**Comment by th-otto** [comment]
> > (review: I cant approve this PR btw - or request changes - just comment)
> 
> Are you sure you know how Github and PRs work? For a PR you don't need write access and since Thorsten already gave you one, you don't need to create and/or approve your own PRs.

I just gave him access a few minutes ago. Just a matter of overlap, and i think he had already prepared that PR earlier.

I'm just a bit irritated because github tells me that there are "no conflicts with the base branch", but i've change a few files with my last commit. Let's see how this goes.

**Comment by paulwratt** [comment]
> > (review: I cant approve this PR btw - or request changes - just comment)
> 
> Are you sure you know how Github and PRs work? For a PR you don't need write access and since Thorsten already gave you one, you don't need to create and/or approve your own PRs.

having write access to the repo is great, but _I_ will only use it for emergencies, I would rather manage my commits through PR's (like I have to with SerenityOS) - The technique @th-otto just described in the freemint list is the same one use by SerenityOS - it creates clean commit history and I can butcher my own clone repo without fear :)

eg: I had to delete my branch and `push --force` it 3x just now to get this PR up :) just because I did not check & pull the `freemint/highwire` repo 1st ( @th-otto made some commits in between, hence my 3x attempts :) - this was a good thing because he removed the "blocks" causing `dos2unix` to skip certain files

**Comment by paulwratt** [comment]
> About the beta6 source:

yeah, forget that comment, I was looking at the repo src, not Peters src, which I confirmed just now is `6` - thanks for confirming that `a` char too, I'll leave it, and it should show up when I get to a native compile (looking at it in QED)

**Comment by th-otto** [comment]
So our version is beta5, and his is beta6? I guess there aren't that many differences. So even without a commit log, might be worth to have a look at it. Is that available somewhere?

**Comment by th-otto** [comment]
BTW, i already compiled with it gcc 4.6.4, and recent libraries. Does start up at least without crashing ;)

**Comment by paulwratt** [comment]
(: thats nice to know, now I dont feel so much like it will be an uphill process, those commits you made certainly help too

I post the Beta6 patch/PR soon, just want to test those access rights with a PR to `gh-pages` branch, plus I have to figure out how to test it  - I think I can enable GH pages on my clone repo and test it there 1st. Like I just said on the freemint list I have some stuff on the SF site which _does_ support php, so I'll generate an HTML version from that, and add any missing php there from the GH repo first.

**Pull request merged**
